name: app_state_codelab
description: A new Flutter project for state management with scoped_model.
publish_to: 'none' # jika hanya untuk lokal

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
